### ISSUE TITLE
Maximum msg payload is fixed to 8KB

### ISSUE THREAD

**Issue by killerwhile** [vert-x3/vertx-mqtt-server#10] opened 2017-02-23 19:18 UTC
`MqttServerImpl` instanciate `MqttDecoder` from `netty-codec-mqtt` library without parameters, which fixes the max possible message payload to 8092 (bytes) (seed https://github.com/netty/netty/blob/4.1/codec-mqtt/src/main/java/io/netty/handler/codec/mqtt/MqttDecoder.java#L64)

This might be a problematic limitation in some use-cases so mqtt-server should have an option to change this limit.

I'd propose to use NetworkOptions.receiveBufferSize to parameter this limit.
See https://github.com/Sqooba/vertx-mqtt-server/tree/msg-more-than-8k branch to somehow illustrate my proposal, while that's probably not the final version ;)

**Comment by ppatierno** [comment] 2017-02-23 19:49
Thanks @killerwhile ... I'll take a look at this. It's even important for an issue reported in the Eclipse Hono project here : https://github.com/eclipse/hono/issues/97

**Comment by ppatierno** [comment] 2017-02-24 08:58
Using the NetworkOptions.receiveBufferSize refers to the max size of the entire MQTT packet.
The max size in the Netty MQTT codec is related to the variable header and payload part; it doesn't take into account the fixed header that could vary from 2 to 5 bytes (because the remaining length can be from 1 to 4 bytes). This bytes should be considered as part of the MQTT packet in order to refer as "receiveBufferSize". I know, they are only max 5 bytes (or at least 2) .... it's more a philosophical choice but I would add a more MQTT specific max buffer size parameter in the MqttServerOptions. 

@killerwhile what do you think ?

**Comment by killerwhile** [comment] 2017-02-24 09:12
Thanks for the other pointer.
I do agree on having a more MQTT payload specific option, while we should ensure that they are somehow aligned (i.e. if NetworkOptions.receiveBufferSize is smaller than max MQTT payload, we should raise a warn)

**Comment by ppatierno** [comment] 2017-02-24 09:19
Yes of course ... agree. I'll go in this direction. Thanks for reporting this issue. I'll update you as soon as possible ;)

**Comment by ppatierno** [comment] 2017-02-26 14:06
I'm closing it on behalf of 89bfdde46de8a188d0a7830917b45b7073e1312a

**Closed by ppatierno** 2017-02-26 14:06 UTC

**Comment by vogler75** [comment] 2022-05-02 11:38
Hi, I have tried to set the MaximumMessageSize to greater than 64k, but this does not work with Websockets. When I set it to greater than 64k a client which sends a message bigger than 64k gets disconnected. Is there a way to set it to a value greate than 64k?

**Comment by vietj** [comment] 2022-05-04 08:19
the issue is about WebSocket limitations, if you set an exception handler you will get 

```
io.netty.handler.codec.http.websocketx.CorruptedWebSocketFrameException: Max frame length of 65536 has been exceeded.
	at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.protocolViolation(WebSocket08FrameDecoder.java:424)
	at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.decode(WebSocket08FrameDecoder.java:286)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)

```

**Comment by vietj** [comment] 2022-05-04 08:29
we will provide in 4.3 a setting to increase this value

**Comment by vogler75** [comment] 2022-05-04 18:48
Great! Thank you!
